version: '3'
services:
  app-1:
    build: ./app
    ports:
      - "8082:8080"
  app-2:
    build: ./app
    ports:
      - "8081:8080"
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app-1
      - app-2
